"""
Export Engine — Generate downloadable CSV summaries and text reports.
"""

from __future__ import annotations

import io
import logging
from datetime import datetime, timezone

import pandas as pd

from src.provenance import format_citation

logger = logging.getLogger(__name__)


def export_studies_csv(df: pd.DataFrame) -> str:
    """Export studies DataFrame to CSV string (for st.download_button)."""
    export_cols = [
        c for c in [
            "study_id", "title", "year", "organization", "url",
            "quality_level", "trust_score", "completeness_score",
            "freshness_score", "resource_count_computed", "has_microdata",
        ]
        if c in df.columns
    ]
    return df[export_cols].to_csv(index=False)


def generate_policy_brief(
    study_row: pd.Series,
    scenario: str = "general",
) -> str:
    """
    Generate a formatted policy brief for a single study.
    Returns markdown text.
    """
    title = study_row.get("title", "Untitled Study")
    org = study_row.get("organization", "Unknown")
    year = study_row.get("year", "N/A")
    abstract = study_row.get("abstract", "No abstract available.")
    url = study_row.get("url", "")
    quality = study_row.get("quality_level", "unknown")
    trust = study_row.get("trust_score", 0)
    completeness = study_row.get("completeness_score", 0)
    flags = study_row.get("quality_flags_list", [])
    resource_count = study_row.get("resource_count_computed", 0)

    # Citation
    citation = format_citation(title, org, year, url)

    # Quality caveats
    caveats = ""
    if quality == "critical":
        caveats = (
            "> ⚠️ **Data Quality Caveat**: This dataset has critical quality issues. "
            "Use with caution and verify findings independently.\n\n"
        )
    elif quality == "warning":
        caveats = (
            "> ℹ️ **Data Quality Note**: Some metadata fields are missing. "
            "Consider this when citing.\n\n"
        )

    flag_text = ""
    if flags:
        flag_text = "**Quality flags**: " + ", ".join(flags) + "\n\n"

    brief = f"""# Policy Brief: {title}

**Prepared**: {datetime.now(timezone.utc).strftime("%d %B %Y")}
**Source**: {org} ({year})
**Scenario**: {scenario.title()}

---

## Key Data Source

{abstract}

## Data Quality Assessment

| Metric | Value |
|---|---|
| Trust Score | {trust:.0%} |
| Completeness | {completeness:.0%} |
| Quality Level | {quality.title()} |
| Resources Available | {resource_count} |

{caveats}{flag_text}## Citation

{citation}

---

*Generated by GenderLens RW — Smart Gender Data Discovery Platform*
"""
    return brief


def generate_comparison_report(df: pd.DataFrame) -> str:
    """Generate a comparison report across multiple studies."""
    now = datetime.now(timezone.utc).strftime("%d %B %Y")

    report = f"# GenderLens RW — Data Comparison Report\n\n"
    report += f"**Generated**: {now}  \n"
    report += f"**Studies compared**: {len(df)}\n\n---\n\n"

    for _, row in df.iterrows():
        title = row.get("title", "Untitled")
        org = row.get("organization", "Unknown")
        year = row.get("year", "N/A")
        trust = row.get("trust_score", 0)
        quality = row.get("quality_level", "unknown")
        report += f"### {title}\n"
        report += f"- **Organization**: {org}\n"
        report += f"- **Year**: {year}\n"
        report += f"- **Trust Score**: {trust:.0%}\n"
        report += f"- **Quality**: {quality.title()}\n\n"

    report += "---\n\n*Generated by GenderLens RW*\n"
    return report
