[theme]
primaryColor = "#5b93df"
backgroundColor = "#1a2f5e"
secondaryBackgroundColor = "#2d51a1"
textColor = "#EEF4FF"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
